"""add driver module entities

Revision ID: 3db46a6ea825
Revises: 9ab1f35d55c5
Create Date: 2026-09-26 15:46:16.014935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db46a6ea825'
down_revision: Union[str, Sequence[str], None] = '9ab1f35d55c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('badge_id', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('duty_status', sa.String(length=50), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_availability_status'), 'drivers', ['availability_status'], unique=False)
    op.create_index(op.f('ix_drivers_duty_status'), 'drivers', ['duty_status'], unique=False)
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_mobile_number'), 'drivers', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_drivers_verification_status'), 'drivers', ['verification_status'], unique=False)
    op.create_table('ambulances',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('driver_id', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('ambulance_type', sa.String(length=50), nullable=False),
    sa.Column('equipment_capabilities', sa.JSON(), nullable=True),
    sa.Column('hospital_affiliation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulances_driver_id'), 'ambulances', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    op.create_index(op.f('ix_ambulances_registration_number'), 'ambulances', ['registration_number'], unique=True)
    op.create_table('driver_documents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('driver_id', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_id'), 'driver_documents', ['id'], unique=False)
    op.create_table('driver_locations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('driver_id', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_locations_driver_id'), 'driver_locations', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_locations_id'), 'driver_locations', ['id'], unique=False)
    op.create_index(op.f('ix_driver_locations_recorded_at'), 'driver_locations', ['recorded_at'], unique=False)
    op.create_table('emergency_responses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('driver_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('response_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_responses_driver_id'), 'emergency_responses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_emergency_responses_id'), 'emergency_responses', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_responses_request_id'), 'emergency_responses', ['request_id'], unique=False)
    op.add_column('emergencies', sa.Column('patient_name', sa.String(length=255), nullable=True))
    op.add_column('emergencies', sa.Column('patient_phone', sa.String(length=50), nullable=True))
    op.add_column('emergencies', sa.Column('pickup_address', sa.Text(), nullable=True))
    op.add_column('emergencies', sa.Column('emergency_type', sa.String(length=100), nullable=True))
    op.add_column('emergencies', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('emergencies', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emergencies', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencies', 'completed_at')
    op.drop_column('emergencies', 'accepted_at')
    op.drop_column('emergencies', 'priority')
    op.drop_column('emergencies', 'emergency_type')
    op.drop_column('emergencies', 'pickup_address')
    op.drop_column('emergencies', 'patient_phone')
    op.drop_column('emergencies', 'patient_name')
    op.drop_index(op.f('ix_emergency_responses_request_id'), table_name='emergency_responses')
    op.drop_index(op.f('ix_emergency_responses_id'), table_name='emergency_responses')
    op.drop_index(op.f('ix_emergency_responses_driver_id'), table_name='emergency_responses')
    op.drop_table('emergency_responses')
    op.drop_index(op.f('ix_driver_locations_recorded_at'), table_name='driver_locations')
    op.drop_index(op.f('ix_driver_locations_id'), table_name='driver_locations')
    op.drop_index(op.f('ix_driver_locations_driver_id'), table_name='driver_locations')
    op.drop_table('driver_locations')
    op.drop_index(op.f('ix_driver_documents_id'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.drop_index(op.f('ix_ambulances_registration_number'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_driver_id'), table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_drivers_verification_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_mobile_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_duty_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_availability_status'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
