"""add_dispatch_timeout_candidate_fields

Revision ID: 5487c5166f5e
Revises: 3db46a6ea825
Create Date: 2026-09-28 09:48:33.429098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5487c5166f5e'
down_revision: Union[str, Sequence[str], None] = '3db46a6ea825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencies', sa.Column('current_candidate_driver_id', sa.String(length=255), nullable=True))
    op.add_column('emergencies', sa.Column('dispatch_offered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emergencies', sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencies', 'response_deadline')
    op.drop_column('emergencies', 'dispatch_offered_at')
    op.drop_column('emergencies', 'current_candidate_driver_id')
    # ### end Alembic commands ###
