"""create emergencies table

Revision ID: 9ab1f35d55c5
Revises: 
Create Date: 2026-09-26 15:01:50.664793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab1f35d55c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('front_photo_path', sa.String(length=500), nullable=False),
    sa.Column('rear_photo_path', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_ambulance_id', sa.String(length=255), nullable=True),
    sa.Column('assigned_driver_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencies_id'), 'emergencies', ['id'], unique=False)
    op.create_index(op.f('ix_emergencies_patient_id'), 'emergencies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergencies_status'), 'emergencies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergencies_status'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_patient_id'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_id'), table_name='emergencies')
    op.drop_table('emergencies')
    # ### end Alembic commands ###
